# Generated by Django 5.1.3 on 2024-11-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sent_requests',
            field=models.ManyToManyField(blank=True, related_name='received_requests', to='core.profile'),
        ),
    ]
