# Generated by Django 5.1.3 on 2024-12-01 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_sent_requests_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
