# Generated by Django 5.1.3 on 2024-12-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_friend_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='requested_by', to='core.profile'),
        ),
    ]
