# Generated by Django 5.1.3 on 2024-12-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_follower_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follower_count',
            field=models.IntegerField(default=100),
        ),
    ]
