# Generated by Django 5.1.3 on 2024-12-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_profile_follower_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follower_count',
        ),
    ]
