# Generated by Django 5.1.3 on 2024-11-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagingFeature', '0002_rename_link_name_chatchannel_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatchannel',
            name='channel_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
